# Generated by Django 5.1.4 on 2025-01-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timg', models.URLField(max_length=500)),
                ('tname', models.CharField(max_length=30)),
            ],
        ),
    ]
