# Generated by Django 5.1.4 on 2025-01-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_team', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
