# Generated by Django 5.1.4 on 2025-02-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_team', '0005_alter_srvdetail_srvheading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='srvdetail',
        ),
    ]
