# Generated by Django 5.1.4 on 2025-02-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_team', '0007_srvdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srvdetail',
            name='srvheading',
            field=models.TextField(max_length=150),
        ),
    ]
