# Generated by Django 5.1.4 on 2025-02-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_team', '0009_alter_srvdetail_srvdetail_alter_srvdetail_srvheading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='srvdetail',
            new_name='AirFreight',
        ),
    ]
