# Generated by Django 5.1.4 on 2025-02-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_team', '0010_rename_srvdetail_airfreight'),
    ]

    operations = [
        migrations.CreateModel(
            name='OceanFreight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(max_length=500)),
                ('srvname', models.CharField(max_length=20)),
                ('srvheading', models.CharField(max_length=80)),
                ('srvdetail', models.CharField(max_length=100)),
                ('srvcontant', models.TextField(max_length=500)),
            ],
        ),
    ]
