# Generated by Django 5.1.4 on 2025-02-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_team', '0013_cargostorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=100)),
                ('info', models.TextField(max_length=500)),
            ],
        ),
    ]
