# Generated by Django 5.1.4 on 2025-01-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='export_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eximg', models.URLField(max_length=500)),
                ('extitle', models.CharField(max_length=20)),
                ('exdesc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='export_product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eximg', models.URLField(max_length=500)),
                ('extitle', models.CharField(max_length=50)),
                ('exdesc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='export_product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eximg', models.URLField(max_length=500)),
                ('extitle', models.CharField(max_length=50)),
                ('exdesc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='export_product3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eximg', models.URLField(max_length=500)),
                ('extitle', models.CharField(max_length=50)),
                ('exdesc', models.TextField(max_length=200)),
            ],
        ),
    ]
