# Generated by Django 5.1.4 on 2025-01-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_dyp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='export_product',
            new_name='export_product0',
        ),
    ]
