# Generated by Django 5.1.4 on 2025-03-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_dyp', '0002_rename_export_product_export_product0'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='export_product0',
            new_name='ExportProduct0',
        ),
        migrations.RenameModel(
            old_name='export_product3',
            new_name='ExportProduct1',
        ),
        migrations.RenameModel(
            old_name='export_product1',
            new_name='ExportProduct2',
        ),
        migrations.RenameModel(
            old_name='export_product2',
            new_name='ExportProduct3',
        ),
    ]
