# Generated by Django 5.1.4 on 2025-04-15 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export_dyp', '0003_rename_export_product0_exportproduct0_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExportProduct0',
            new_name='ExportProduct',
        ),
        migrations.DeleteModel(
            name='ExportProduct1',
        ),
        migrations.DeleteModel(
            name='ExportProduct2',
        ),
        migrations.DeleteModel(
            name='ExportProduct3',
        ),
    ]
