# Generated by Django 5.1.4 on 2025-01-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imimg', models.URLField(max_length=100)),
                ('imtitle', models.CharField(max_length=50)),
                ('imdtl', models.TextField(max_length=500)),
            ],
        ),
    ]
